# Generated by Django 5.0.7 on 2024-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bread_fruits_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='nav_category',
            field=models.ManyToManyField(to='shop.nav_category'),
        ),
        migrations.AddField(
            model_name='fruits',
            name='nav_category',
            field=models.ManyToManyField(to='shop.nav_category'),
        ),
        migrations.AddField(
            model_name='vegetables',
            name='nav_category',
            field=models.ManyToManyField(to='shop.nav_category'),
        ),
        migrations.AlterField(
            model_name='bread',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
