# Generated by Django 5.0.7 on 2024-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bread_nav_category_fruits_nav_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bread',
            name='nav_category',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='nav_category',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='nav_category',
        ),
        migrations.AlterField(
            model_name='fruits',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=150, unique=True),
        ),
    ]
